openapi: 3.0.3
info:
  title: MassBank Minio API
  version: "0.1"
servers:
- url: https://localhost:8081/
paths:
  /config/addConnection:
    post:
      operationId: addConnection
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Connection'
      responses:
        "200":
          description: OK
        "409":
          description: Could not insert dataset
  /config/connections:
    delete:
      operationId: deleteAllConnections
      responses:
        "200":
          description: OK
        "400":
          description: error
    get:
      operationId: getConnections
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Connection'
                type: array
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal error
components:
  schemas:
    Connection:
      example:
        filter:
          bucket: bucket
          prefix: prefix
          suffix: suffix
        minio:
          endpoint: endpoint
          password: password
          username: username
          useSsl: true
        target:
          password: password
          authmethod: authmethod
          url: url
          username: username
        validate: massbankv2
      properties:
        minio:
          $ref: '#/components/schemas/Connection_minio'
        target:
          $ref: '#/components/schemas/Connection_target'
        filter:
          $ref: '#/components/schemas/Connection_filter'
        validate:
          default: massbankv2
          type: string
      type: object
    Connection_minio:
      example:
        endpoint: endpoint
        password: password
        username: username
        useSsl: true
      properties:
        endpoint:
          nullable: false
          type: string
        username:
          type: string
        password:
          type: string
        useSsl:
          type: boolean
      type: object
    Connection_target:
      example:
        password: password
        authmethod: authmethod
        url: url
        username: username
      properties:
        url:
          type: string
        username:
          type: string
        password:
          type: string
        authmethod:
          type: string
      type: object
    Connection_filter:
      example:
        bucket: bucket
        prefix: prefix
        suffix: suffix
      properties:
        bucket:
          type: string
        prefix:
          type: string
        suffix:
          type: string
      type: object
